name: Deta Deploy

on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  NODE_ENV: production
  APP_NAME: FreeText
  APP_DETA_PROJECT_KEY: ${{ secrets.APP_DETA_PROJECT_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deta Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup environments
        run: env | grep ^NODE_ENV >> .env && env | grep ^APP_ >> .env

      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'yarn'

      - name: Install dependensis
        run: yarn install --production=false

      - name: Build code
        run: yarn build

      - name: Add index.js
        run: echo "module.exports = require('./dist')" > index.js

      - name: Publish
        uses: BogDAAAMN/deta-deploy-action@v1.0.1
        with:
          deta-access-token: ${{ secrets.DETA_ACCESS_TOKEN }}
          deta-name: 'textbin'
          deta-project: 'default'
          deta-project-dir: '.'

      - name: Update Deta environments
        run: |
          export DETA_ACCESS_TOKEN=${{ secrets.DETA_ACCESS_TOKEN }}
          ~/.deta/bin/deta update -e .env
